## Ficha 4 - Resolução

In [194]:
import matplotlib.pyplot as plt
import numpy as np
import numpy.random as rd
import sklearn.datasets as dt
import scipy.linalg as la
import pickle

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import confusion_matrix

In [195]:
QuestDic = pickle.load(open("A46484_Ficha4_Respostas.p", "rb"))
print(QuestDic.keys())
print("Nome: ",QuestDic['nome'])
print("Número: ",QuestDic['numero'])
print("Pergunta 1:\n ",QuestDic['Q001'])
print("Pergunta 2:\n ",QuestDic['Q002'])
print("Pergunta 3:\n ",QuestDic['Q003'])

dict_keys(['Q001', 'Q002', 'Q003', 'nome', 'numero'])
Nome:  Duarte Alexandre Pedro Gonçalves
Número:  A46484
Pergunta 1:
  [[0. 1. 0. 0.]
 [0. 1. 0. 0.]]
Pergunta 2:
  [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
Pergunta 3:
  [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


### Exercício 1 <br>
No ficheiro A46484_Q001_data.p encontra-se disponível uma variavel independente x e uma variavel dependente y. Pretende-se estimar a variavel y atraves de uma regressão polinomial da variavel x, minimizando o erro quadratico médio.

In [196]:
D = pickle.load(open("A46484_Q001_data.p", "rb"))
print(D.keys())
x = D['x']
y = D['y']
f = D['folds']

print("X.shape: ",X.shape)
print("y.shape: ",y.shape)
print("f.shape: ",f.shape)

dict_keys(['x', 'y', 'folds'])
X.shape:  (3, 2934)
y.shape:  (164,)
f.shape:  (164,)


#### (a) Considere o conjunto de treino composto pelo “fold” 0, e o conjunto de teste composto pelo “fold” 1. Considere ainda que, atraves da minimização do erro quadrático medio do conjunto de treino, se estimou um modelo regressão polinomial de 4º ordem: $y = w_0 + w_1x + w_2x^2 + w_3x^3 + w_4x^4$.

In [197]:
#Treino 
x0 = x[f==0] 
y0 = y[f==0]

#Teste
x1 = x[f==1] 
y1 = y[f==1]

# Adicionar 2ª dimensão
X0 = x0[:,np.newaxis]
X1 = x1[:,np.newaxis]
print("X0.shape: ",X0.shape)
print("X1.shape: ",X1.shape)

# Criar modelo de regressão linear
poly = PolynomialFeatures(degree=4).fit(X0)
X0a = poly.transform(X0)
X1a = poly.transform(X1)

# Criar modelo de regressão linear
lr = LinearRegression().fit(X0a, y0)
y0e = lr.predict(X0a)
y1e = lr.predict(X1a)

print("i. No conjunto de treino, o erro absoluto medio e igual a 0.49: ", round(np.mean(np.abs(y0-y0e)), 2))
print("ii. No conjunto de treino, o erro quadratico médio e igual a 0.12: ", round(np.mean((y0-y0e)**2), 2))

#Resposta ii)

X0.shape:  (98, 1)
X1.shape:  (66, 1)
i. No conjunto de treino, o erro absoluto medio e igual a 0.49:  0.28
ii. No conjunto de treino, o erro quadratico médio e igual a 0.12:  0.12


#### (b) Considere o conjunto de treino composto pelo “fold” 1, e o conjunto de teste composto pelo “fold” 0. Considere ainda que, atraves da minimização do erro quadrático médio do conjunto de treino, se estimou um modelo regressão polinomial de 3ª ordem: $y = w_0 + w_1x + w_2x^2 + w_3x^3$.

In [198]:
#Treino 
x1 = x[f==1] 
y1 = y[f==1]

#Teste
x0 = x[f==0] 
y0 = y[f==0]

# Adicionar 2ª dimensão
X0 = x0[:,np.newaxis] #Teste
X1 = x1[:,np.newaxis] #Treino
print("X0.shape: ",X0.shape)
print("X1.shape: ",X1.shape)

# Criar modelo de regressão linear
poly = PolynomialFeatures(degree=3).fit(X1)
X0a = poly.transform(X0)
X1a = poly.transform(X1)

# Criar modelo de regressão linear
lr = LinearRegression().fit(X1a, y1)
y0e = lr.predict(X0a)
y1e = lr.predict(X1a)

w0 = lr.intercept_
print("\ni. Arredondando a zero casas decimais, o valor de w0 e -9: ", round(w0, 0))
print("ii. No conjunto de teste, o erro absoluto medio e igual a 0.52: ",round(np.mean(np.abs(y0-y0e)),2))

#Resposta ii)

X0.shape:  (98, 1)
X1.shape:  (66, 1)

i. Arredondando a zero casas decimais, o valor de w0 e -9:  0.0
ii. No conjunto de teste, o erro absoluto medio e igual a 0.52:  0.52


#### Respostas

In [199]:
QuestDic['Q001'][0,:] = np.array([0,1,0,0]) #ii
QuestDic['Q001'][1,:] = np.array([0,1,0,0]) #ii

### Exercício 2

In [200]:
D = dt.load_diabetes()
print(D.keys())
x = D['data']
y = D['target']
print("x.shape: ",x.shape)
print("y.shape: ",y.shape)

X1 = x[:361,:] #Treino
X2 = x[361:,:] #Teste
y1 = y[:361]
y2 = y[361:]
print("\nX1.shape: ",X1.shape)
print("X2.shape: ",X2.shape)
print("y1.shape: ",y1.shape)
print("y2.shape: ",y2.shape)

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])
x.shape:  (442, 10)
y.shape:  (442,)

X1.shape:  (361, 10)
X2.shape:  (81, 10)
y1.shape:  (361,)
y2.shape:  (81,)


#### (a) Considere o modelo de regressao polinomial de 2ª ordem que minimiza o erro quadratico médio no conjunto de treino.

In [201]:
# Criar modelo de regressão linear
poly = PolynomialFeatures(degree=2).fit(X1)
X1a = poly.transform(X1)
X2a = poly.transform(X2)

lr = LinearRegression().fit(X1a, y1)
r2_1 = lr.score(X1a, y1)
r2_2 = lr.score(X2a, y2)
print("i. No conjunto de teste, o coeficiente de determinacao, R2, e igual a 0.595: ", round(r2_2, 3))
print("ii. No conjunto de treino, o coeficiente de determinacao, R2, e igual a 0.78: ", round(r2_1, 2))
#Resposta iv) 

i. No conjunto de teste, o coeficiente de determinacao, R2, e igual a 0.595:  0.458
ii. No conjunto de treino, o coeficiente de determinacao, R2, e igual a 0.78:  0.6


#### (b) Considere que utiliza funcao Lasso (sub-modulo linear model do sklearn) para uma regressao polinomial de 4ª ordem dos dados de treino. Instancie o regressor somente com os seguintes parametros:  Lasso(random state=42,alpha=0.01)

In [202]:
# Criar modelo de regressão linear
poly = PolynomialFeatures(degree=4).fit(X1)
X1a = poly.transform(X1)
X2a = poly.transform(X2)

lr = Lasso(random_state=42, alpha=0.01).fit(X1a, y1)
print("i. Excluindo w0, o numero de coeficientes do polinomio com valor absoluto maior que 219 e igual a 8 :",np.sum(lr.coef_>219))

y2e = lr.predict(X2a)
print("ii. No conjunto de teste, o erro quadratico medio e igual a 2612.19 ",round(np.mean((y2-y2e)**2),2))

#Resposta iii)

i. Excluindo w0, o numero de coeficientes do polinomio com valor absoluto maior que 219 e igual a 8 : 8
ii. No conjunto de teste, o erro quadratico medio e igual a 2612.19  2612.19


#### (c)

In [203]:
def c(x,degree):
    poly = PolynomialFeatures(degree=degree).fit(x)
    X1a = poly.transform(x)
    lr = Lasso(random_state=42, alpha=0.01).fit(X1a, y1)
    return lr.n_features_in_

print("i. O numero de coeficientes, incluindo w0, numa regressao polinomial de ordem 2, e igual a 66: ",c(X1,2))
print("ii. O numero de coeficientes, incluindo w0, numa regressao polinomial de ordem 4, e igual a 1009.", c(X1,4))
#Resposta i)

i. O numero de coeficientes, incluindo w0, numa regressao polinomial de ordem 2, e igual a 66:  66
ii. O numero de coeficientes, incluindo w0, numa regressao polinomial de ordem 4, e igual a 1009. 1001


#### Respostas

In [204]:
QuestDic['Q002'][0,:] = np.array([0,0,0,1]) #iV
QuestDic['Q002'][1,:] = np.array([0,0,1,0]) #iii
QuestDic['Q002'][2,:] = np.array([1,0,0,0]) #i

### Exercício 3 <br>
No ficheiro A46484_Q003_data.p, encontra-se um conjunto de dados bidimensionais divididos em duas classes Ω ={$w_0; w_1$} (negativos e positivos). Ha duas variaveis num dicionario: X e uma matriz de dados, e y e um array com as classes dos dados. Considere o seguinte modelo linear de classificacao: <br> 
$y = w^Tx = w_0 + w_1x_1 + w_2x_2$, <br>
com $x \in w_1$ para $y ≥ 0$, e para $w = [w_0; w_1; w_2]^T$ e $x=[1; x_1; x_2]^T$. <br>

Considere ainda que o vetor $wMSE$ e o vetor de pesos que minimiza o erro quadratico medio deste conjunto: $E = \frac 1N\sum(y[n] − y[n])^2$, <br>
onde N e o numero total de pontos, e n = 1,...,N. As saidas desejadas sao: $ y[n] = −1$ para $x[n] \in w_0$ e y[n] = +1 para $x[n] \in w_1$.

In [205]:
D = pickle.load(open("A46484_Q003_data.p", "rb"))
print(D.keys())
x = D['X']
y = D['y']
print("x.shape: ",x.shape)
print("y.shape: ",y.shape)

X = np.vstack((np.ones(x.shape[1]), x))
idx = np.argsort(y)
y = y[idx]
X = X[:,idx]
print("X.shape: ",X.shape)
print("y.shape: ",y.shape)

# Colocar w0 a -1 de modo a comparar posteriormente
y[y==0] = -1

dict_keys(['y', 'X'])
x.shape:  (2, 2934)
y.shape:  (2934,)
X.shape:  (3, 2934)
y.shape:  (2934,)


#### (a) Consider o classificador com o seguinte vetor de pesos w = [0:00; 0:86; −0:52].

In [206]:
w  = np.array([0.00, 0.86, -0.52])
ye = np.dot(w.T,X)

# "y>=0 são w1" e "w1 fica +1"
yeCopy = ye.copy()
yeCopy[ye<0] = -1
yeCopy[ye>=0]=  1 

CM = confusion_matrix(y, yeCopy)
print("\nMatriz de confusao:\n",CM)
# Se 0 > Negativo 
#    1 > Positivo
# Tem-se:
#
#        estimado
#          0  1
# real  0 TN FP
#       1 FN TP

precisao = CM[1,1]/(CM[1,1]+CM[0,1])
acertosTotal = CM[0,0]+CM[1,1]
recall = CM[1,1]/(CM[1,1]+CM[1,0])
print("\ni. O valor da precisao e de 0.916: ",round(precisao,4))
print("ii. O numero total de acertos e de 2574: ", acertosTotal)
print("iii. O valor do recall e de 0.888: ", round(recall,3))
print("iv. O numero de acertos na classe w1 e de 1763: ", CM[1,1])

#Resposta ii)


Matriz de confusao:
 [[ 801  155]
 [ 205 1773]]

i. O valor da precisao e de 0.916:  0.9196
ii. O numero total de acertos e de 2574:  2574
iii. O valor do recall e de 0.888:  0.896
iv. O numero de acertos na classe w1 e de 1763:  1773


#### (b) Considere o classificador com vetor de pesos, wMSE, que minimiza o erro quadratico medio do conjunto.

In [207]:
Rx = np.dot(X, X.T)
rxy = np.dot(X, y.T)
wMSE = np.dot(la.pinv(Rx), rxy)

ye = np.dot(wMSE.T, X)
yeCopy = ye.copy()
yeCopy[ye<0] = -1
yeCopy[ye>=0] = 1

cm = confusion_matrix(y, yeCopy)
print("Matriz de Confusão: \n", cm)

print("\ni. O vetor que minimiza o erro quadratico medio e wMSE = [0.089; 0.279; −0.016]: ",np.around(wMSE,3))
print("ii. O erro quadratico medio e igual a 0.485: ",round(np.mean((y-ye)**2),3))
#Resposta iii)


Matriz de Confusão: 
 [[ 899   57]
 [   3 1975]]

i. O vetor que minimiza o erro quadratico medio e wMSE = [0.089; 0.279; −0.016]:  [ 0.089  0.279 -0.016]
ii. O erro quadratico medio e igual a 0.485:  0.485


#### (c) Consider o classificador com o seguinte vetor de pesos w = [0:00; 0:87; 0:48].

In [208]:
w  = np.array([0.00, 0.87, 0.48])
ye = np.dot(w.T,X)

yeCopy = ye.copy()
yeCopy[ye<0] = -1
yeCopy[ye>=0]=  1 

cm = confusion_matrix(y, yeCopy)
print("Matriz de Confusão: \n", cm)

print("\ni. A taxa de falsos alarmes e de 0.281: ",round(cm[0,1]/(cm[0,0]+cm[0,1]),3))
print("ii. O numero de acertos na classe w0 e de 692: ", cm[0,0])
#Resposta ii)

Matriz de Confusão: 
 [[ 692  264]
 [  95 1883]]

i. A taxa de falsos alarmes e de 0.281:  0.276
ii. O numero de acertos na classe w0 e de 692:  692


#### Respostas

In [209]:
QuestDic['Q003'][0,:] = np.array([0,1,0,0]) #ii
QuestDic['Q003'][1,:] = np.array([0,0,1,0]) #iii
QuestDic['Q003'][2,:] = np.array([0,1,0,0]) #ii
pickle.dump(QuestDic,open('A46484_Ficha4_Respostas.p','wb'))

### RESOLUÇÃO

In [210]:
QuestDic = pickle.load(open("A46484_Ficha4_Respostas.p", "rb"))
print("Pergunta 1:\n ",QuestDic['Q001'])
print("Pergunta 2:\n ",QuestDic['Q002'])
print("Pergunta 3:\n ",QuestDic['Q003'])

Pergunta 1:
  [[0. 1. 0. 0.]
 [0. 1. 0. 0.]]
Pergunta 2:
  [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
Pergunta 3:
  [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
