In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
cL = ['Life isnt\t easy',
      'for the Pin Cushion Queen.',
      'When she sits on her thorne',
      'pins push through her spleen.']

In [4]:
cv = CountVectorizer().fit(cL)
a = cv.vocabulary_

In [21]:
v = cv.transform(cL)
print(v.toarray())
v = cv.get_feature_names_out()
print(v)
vD = cv.vocabulary_ 
print(vD)

[[0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 1]
 [0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 1 0]]
['cushion' 'easy' 'for' 'her' 'isnt' 'life' 'on' 'pin' 'pins' 'push'
 'queen' 'she' 'sits' 'spleen' 'the' 'thorne' 'through' 'when']
{'life': 5, 'isnt': 4, 'easy': 1, 'for': 2, 'the': 14, 'pin': 7, 'cushion': 0, 'queen': 10, 'when': 17, 'she': 11, 'sits': 12, 'on': 6, 'her': 3, 'thorne': 15, 'pins': 8, 'push': 9, 'through': 16, 'spleen': 13}


In [23]:
voc = vD.keys()
n = vD.values()


In [24]:
for i in range(len(v)):
    print(v[i], vD[v[i]])

cushion 0
easy 1
for 2
her 3
isnt 4
life 5
on 6
pin 7
pins 8
push 9
queen 10
she 11
sits 12
spleen 13
the 14
thorne 15
through 16
when 17
