In [2]:
import numpy as np
import matplotlib as plt

In [3]:
a = np.reshape(np.arange(1,7),(2,3))
print(a,a.shape)
b = np.arange(10,13)
print(b,b.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[10 11 12] (3,)


In [4]:
b2 = np.array([[10],[11],[12]])
print(b2,b2.shape)

[[10]
 [11]
 [12]] (3, 1)


In [5]:
b2.T #transposto

array([[10, 11, 12]])

In [6]:
b[:,np.newaxis] #criação de um novo eixo (3x1)
b[np.newaxis,:]#criação de um novo eixo (1x3)

array([[10, 11, 12]])

In [7]:
c = np.hstack((a,b))
print(c,c.shape)


KeyboardInterrupt



In [ ]:
X = np.random.rand(2,1000)+10
plt.plot(X[0,:],X[1,:],'.')
plt.grind(True)
plt.axis('scaled')

AttributeError: module 'matplotlib' has no attribute 'plot'

In [10]:
import sklearn.datasets as dt


In [11]:
D = dt.load_breast_cancer()
D.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [12]:

X = D.data
Y = D.target
print(X.shape)
print(Y.shape)

(569, 30)
(569,)


In [14]:
D['target_names']
print(D['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [15]:
print(D.filename)

breast_cancer.csv
